{% set name = "ragel" %}
{% set version = "6.10" %}
{% set hash_type = "sha256" %}
{% set hash_val = "5f156edb65d20b856d638dd9ee2dfb43285914d9aa2b6ec779dac0270cd56c3f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.colm.net/files/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
  patches:
    - patches/0001-Fix-undeclared-setiosflags-function.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler("cxx") }}

about:
  home: https://www.colm.net/open-source/ragel/
  license: GPLv2
  license_file: COPYING
  summary: Ragel State Machine Compiler
  description: |
    Ragel provides a very flexible interface to the host language that attempts
    to place minimal restrictions on how the generated code is integrated into
    the application. The generated code has no dependencies.

extra:
  recipe-maintainers:
    - rmax
