appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iHMmOIjVqQZpOK8Snqj5yAI9QCMWPTh1lrDwjWN8B6YDn4BC6jE5hRO+vMxPM9w8GhkpQVvLVep0H4dtx5goqpc5o8jYPeM451DzF6h/GpqixmefZh4PSUPDKQ1mqqFRqoohDqNpu17t3qviaCJLteP7dSRdQon4mQTMxJLoqSML73SHbBfwqbbg+fQeTVMhuS+DPv1DjtV42Efu45jWyWyvcD6MeT47IHoNmCJE9SyZKgrjbnS1fR4ykVetGTcxCf9KfotrEkjLjw7xJUxSDGaCApHYakI0J4AagTLqh8QL11uL4lyB/seHS7pM3rEfEt0UKd0y8gcklQ5jxGk5FX2feuInT//ECnPuA51Vw2kcZqDhi27H76mdLncSz7jwesZ2dr4Onx9m9+A6wO9HzH/KooXKbSlnFaNsyWSCEI+dGudeVehH1F6Yon7tJPu2BvBR2l91bjuhYcVW9ZxplGScrDy0zDdfw034m0uVvVXyBXeIVr8g/3HK5ltn4DKVHGhzNMKyFGNQ8XE403C+zr5SJq0zLx0bgCIUqQiG/esFziRyBl8vVAeNnS5V183SwshJu3iv671dANGsv8PjqjixHJepyl1hzblrNZh56yoyEofeu3z04xEqCPWwV5hG7pz5tiF80ecDIxl0EdEN5m84o9z/KetWaV/AYV3Xoos=}
conda_forge_output_validation: true
